import Link from 'next/link';
import { ArrowRight, Check, Fingerprint, LockKeyhole, MoveUpRight, ShieldCheck } from 'lucide-react';
import { AccordionApp } from '@/components/card-split-accordian';
import { TrustTimeline } from '@/components/TrustTimeline';

const proofSteps = [
    { id: 1, title: 'Capture the original', icon: <Fingerprint className="size-5 text-coral" />, content: 'The issuer starts with the original PDF bytes. No screenshots, previews, or rendered copies are used as the source of truth.' },
    { id: 2, title: 'Create a fingerprint', icon: <LockKeyhole className="size-5 text-mint-ink" />, content: 'A SHA-256 digest turns the file into a compact fingerprint. One changed character produces a different digest.' },
    { id: 3, title: 'Attach the proof', icon: <ShieldCheck className="size-5 text-ink/60" />, content: 'The digest is signed with Ed25519 and stored in the PDF metadata as a structured VeriTrail manifest.' },
    { id: 4, title: 'Verify anywhere', icon: <Check className="size-5 text-coral" />, content: 'Anyone with the file can inspect the manifest, recalculate the digest, and see whether the document still matches.' },
];

export default function Home() {
    return (
        <main className="grid-paper min-h-[calc(100vh-89px)] overflow-hidden">
            <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-14 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-24">
                <div className="max-w-2xl">
                    <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-mint/30 bg-mint/10 px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.18em] text-mint-ink"><span className="size-1.5 rounded-full bg-mint" /> Built for the paper trail</div>
                    <h1 className="text-5xl font-semibold leading-[1.08] tracking-[-.06em] sm:text-7xl">Proof for every <span className="text-coral">document.</span></h1>
                    <p className="mt-7 max-w-lg text-base leading-7 text-ink/55">VeriTrail gives your PDFs a cryptographic chain of custody. Issue once, verify anywhere, and know when something has changed.</p>
                    <div className="mt-9 flex flex-wrap gap-3"><Link href="/issue" className="group flex items-center gap-3 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white transition hover:bg-ink/90">Issue a document <ArrowRight size={16} className="transition group-hover:translate-x-1" /></Link><Link href="/verify" className="rounded-full border border-ink/15 bg-white/60 px-5 py-3 text-sm font-semibold transition hover:bg-white">Verify a document</Link></div>
                    <div className="mt-14 flex items-center gap-7 text-[11px] text-ink/45"><span className="flex items-center gap-2"><LockKeyhole size={14} /> Ed25519 signatures</span><span className="flex items-center gap-2"><Fingerprint size={14} /> SHA-256 fingerprints</span></div>
                </div>
                <div className="relative mx-auto w-full max-w-[510px]"><div className="absolute -right-10 -top-10 size-40 rounded-full border border-coral/20" /><div className="relative rounded-[2rem] border border-ink/10 bg-white/75 p-5 shadow-2xl shadow-ink/10 backdrop-blur"><div className="flex items-center justify-between border-b border-ink/10 pb-5"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-ink/40">Trust record · 000184</p><p className="mt-2 text-sm font-semibold">employment_certificate.pdf</p></div><span className="flex size-9 items-center justify-center rounded-full bg-mint/15 text-mint-ink"><ShieldCheck size={19} /></span></div><div className="py-8"><div className="mx-auto max-w-[260px] border border-ink/10 bg-paper px-7 py-8 shadow-sm"><div className="mb-8 flex justify-between"><span className="h-2 w-14 bg-ink/15" /><span className="size-5 rounded-full border-2 border-coral/50" /></div><div className="text-center"><p className="font-mono text-[8px] tracking-[.18em] text-ink/40">CERTIFICATE OF AUTHENTICITY</p><div className="mx-auto mt-4 h-px w-24 bg-coral/60" /><p className="mt-5 text-[13px] font-semibold">Verified original</p><p className="mt-2 text-[9px] text-ink/40">Issued 01 October 2026</p></div><div className="mt-12 flex justify-between"><span className="h-1.5 w-16 bg-ink/10" /><span className="h-1.5 w-10 bg-ink/10" /></div></div></div><div className="border-t border-ink/10 pt-5"><TrustTimeline /></div></div><div className="absolute -bottom-5 -left-5 rounded-2xl border border-mint/30 bg-mint/10 px-4 py-3 shadow-xl shadow-ink/5"><p className="flex items-center gap-2 text-xs font-semibold text-mint-ink"><Check size={15} /> Integrity confirmed</p><p className="mt-1 pl-5 font-mono text-[9px] text-mint-ink/60">digest matches original</p></div></div>
            </section>
            <section className="border-t border-ink/10 bg-[#ecece5] px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-coral">The short version</p><h2 className="mt-4 max-w-sm text-3xl font-semibold tracking-[-.05em]">A paper trail you can actually inspect.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-ink/55">Every signed PDF carries the same quiet sequence: capture what arrived, prove what changed, and make the result legible.</p></div><AccordionApp items={proofSteps} /></div></section>
            <section className="border-t border-ink/10 bg-white/40"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-6 py-8 text-sm text-ink/50 lg:flex-row lg:items-center lg:justify-between lg:px-10"><p>Trusted by teams who need their records to hold up.</p><div className="flex flex-wrap gap-x-8 gap-y-3 font-mono text-[10px] uppercase tracking-[.18em] text-ink/30"><span>Legal ops</span><span>Education</span><span>Finance</span><span>Public records</span></div><Link href="/verify" className="flex items-center gap-2 font-semibold text-ink">Try the verifier <MoveUpRight size={15} /></Link></div></section>
        </main>
    );
}
