'use client';
import { useState } from 'react';
import { ArrowLeft, Check, Download, FileText, LockKeyhole } from 'lucide-react';
import Link from 'next/link';
import { Dropzone } from '@/components/Dropzone';
import { TrustTimeline } from '@/components/TrustTimeline';

export default function IssuePage() {
  const [file, setFile] = useState<File>(); const [done, setDone] = useState(false);
  const issue = () => { if (file) setDone(true); };
  return <main className="mx-auto max-w-6xl px-6 pb-20 pt-10 lg:px-10"><Link href="/" className="mb-12 flex items-center gap-2 text-xs text-ink/45 hover:text-ink"><ArrowLeft size={14} /> Back home</Link><div className="mx-auto max-w-3xl"><div className="mb-10"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-coral">Issuer workspace</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Make it verifiable.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-ink/50">Create a tamper-evident record for a PDF. VeriTrail hashes the original bytes, signs the digest, and embeds the proof back into the file.</p></div><div className="mb-10 rounded-3xl border border-ink/10 bg-white/55 p-6 sm:p-8"><TrustTimeline /><div className="mt-10">{done ? <div className="flex flex-col items-center rounded-2xl border border-mint/25 bg-mint/10 p-10 text-center"><span className="grid size-14 place-items-center rounded-full bg-mint text-white"><Check size={27} /></span><h2 className="mt-5 text-xl font-semibold">Your document is signed.</h2><p className="mt-2 max-w-sm text-xs leading-5 text-ink/55">The VeriTrail manifest has been attached to <strong>{file?.name}</strong>.</p><button className="mt-7 flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-xs font-semibold text-white"><Download size={15} /> Download stamped PDF</button></div> : <><Dropzone onFile={setFile} /><div className="mt-5 flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-3">{file && <><span className="grid size-9 shrink-0 place-items-center rounded-lg bg-coral/10 text-coral"><FileText size={17} /></span><div className="min-w-0"><p className="truncate text-xs font-semibold">{file.name}</p><p className="font-mono text-[10px] text-ink/40">{(file.size / 1024 / 1024).toFixed(2)} MB · ready to sign</p></div></>}</div><button onClick={issue} disabled={!file} className="flex shrink-0 items-center gap-2 rounded-full bg-coral px-5 py-3 text-xs font-semibold text-white transition hover:bg-coral/90 disabled:cursor-not-allowed disabled:opacity-30"><LockKeyhole size={14} /> Sign document</button></div></>}</div></div><p className="text-center font-mono text-[10px] text-ink/35">Your file is processed locally in this demo. Private keys never leave the issuer boundary.</p></div></main>;
}