'use client';
import { useState } from 'react';
import { ArrowLeft, CalendarDays, Copy, FileCheck2, Fingerprint } from 'lucide-react';
import Link from 'next/link';
import { Dropzone } from '@/components/Dropzone';
import { HeuristicReport } from '@/components/HeuristicReport';
import { StatusBanner } from '@/components/StatusBanner';
import { TrustTimeline } from '@/components/TrustTimeline';
import type { VerificationState } from '@/types';

export default function VerifyPage() {
  const [state, setState] = useState<VerificationState>('pending'); const [file, setFile] = useState<File>();
  const inspect = (selected: File) => { setFile(selected); setState(selected.name.toLowerCase().includes('tampered') ? 'tampered' : 'verified'); };
  return <main className="mx-auto max-w-6xl px-6 pb-20 pt-10 lg:px-10"><Link href="/" className="mb-12 flex items-center gap-2 text-xs text-ink/45 hover:text-ink"><ArrowLeft size={14} /> Back home</Link><div className="mx-auto max-w-3xl"><div className="mb-10"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-coral">Verifier workspace</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Does it hold up?</h1><p className="mt-4 max-w-xl text-sm leading-6 text-ink/50">Drop in any PDF to inspect its embedded manifest, compare its content fingerprint, and validate the issuer signature.</p></div><div className="rounded-3xl border border-ink/10 bg-white/55 p-6 sm:p-8"><StatusBanner state={state} />{state === 'pending' ? <div className="mt-6"><Dropzone onFile={inspect} /></div> : <><div className="mt-8"><TrustTimeline /></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-ink/10 bg-white/60 p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-ink/40">Document</span><FileCheck2 size={15} className="text-mint-ink" /></div><p className="mt-3 truncate text-xs font-semibold">{file?.name}</p><p className="mt-1 text-[10px] text-ink/40">PDF · {((file?.size ?? 0) / 1024 / 1024).toFixed(2)} MB</p></div><div className="rounded-xl border border-ink/10 bg-white/60 p-4"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-ink/40">Issued</span><CalendarDays size={15} className="text-coral" /></div><p className="mt-3 text-xs font-semibold">01 October 2026</p><p className="mt-1 text-[10px] text-ink/40">Issuer: VeriTrail demo</p></div></div>{state === 'tampered' && <div className="mt-3 rounded-xl border border-coral/20 bg-coral/5 p-4"><p className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-coral-ink"><Fingerprint size={14} /> Digest mismatch</p><p className="mt-2 break-all font-mono text-[10px] leading-5 text-ink/50">expected 9e5c...f81a · received 3a20...9d02</p></div>}<button onClick={() => { setState('pending'); setFile(undefined); }} className="mt-6 flex items-center gap-2 text-xs font-semibold text-ink/55 hover:text-ink"><Copy size={14} /> Inspect another file</button></>}</div>{state === 'verified' && <div className="mt-4 rounded-3xl border border-ink/10 bg-ink p-6 text-white"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-white/40">Signed fingerprint</p><p className="mt-4 break-all font-mono text-xs leading-6 text-mint">8f3a7c1d5e2b9a4c...c42e91f</p></div>}</div></main>;
}